.TH ELM-GET "1" "June 2014" "elm-get 0.12.3" "User Commands"
.SH NAME
elm-get \- Install and publish elm libraries
.SH DESCRIPTION
elm\-get 0.1.2: The Elm Package Manager (c) Evan Czaplicki 2013\-2014
.IP
install and publish elm libraries
.SH SYNOPSIS
.B elm-get
\fICOMMAND\fR
.SS "Available options:"
.TP
\fB\-h\fR,\-\-help
Show this help text
.SS "Available commands:"
.TP
install
Install libraries in the local project.
.TP
publish
Publish project to the central repository
.IP
.SS "Available options:"
.TP
\fB\-h\fR,\-\-help
Show this help text
.SS "Available commands:"
.TP
install
Install libraries in the local project.
.TP
publish
Publish project to the central repository
.PP
To learn more about a command called COMMAND, just do: elm\-get COMMAND \fB\-\-help\fR
